; COLOR EXPLANATION
; main, sidebar, player = background
; card                  = cards, tracklist, dropdowns, input fields
; shadow                = text on button, tab active & selected row
; selected row          = selected song & tab
; button-active         = play button, outline on focused input
; button                = all other buttons
; button-disabled       = volume & seekbar background, scrollbar handle, borders, hover

[main]
text               = dcd7ba
subtext            = a09cac
main               = 1F1F28
sidebar            = 1F1F28
player             = 1F1F28
card               = 363646
shadow             = 363646
selected-row       = 957FB8
button             = dcd7ba
button-active      = 5d57a3
button-disabled    = 957FB8
tab-active         = bde6fb
notification       = 363646
notification-error = E46876
misc               = 1F1F28
