packages:
  arch:
    - lunatask
    - celluloid-git
    - slack-desktop-wayland
    - todoist-appimage
    - ferdium-bin
    - gearlever
    - chezmoi
    - bruno-bin
    - vivaldi
    - vesktop-bin
    - bitwarden
    - rbw
    - claude-code
    - twist
    - grayjay-bin
    - backrest
    - nano
    - direnv
