
exec-once = xhost + local:
exec-once = easyeffects --gapplication-service
exec-once = ~/.config/swaylock/lock-if-inactive.sh
exec-once = ~/.local/bin/notifications/packages.sh
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = xprop -root -f _XWAYLAND_GLOBAL_OUTPUT_SCALE 32c -set _XWAYLAND_GLOBAL_OUTPUT_SCALE 1
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec = [ "$(pgrep dunst)" ]  && pkill dunst; dunst -config ~/.config/dunst/kanagawa.conf
exec = [ "$(pgrep waybar)" ] && pkill waybar; waybar --config ~/.config/waybar/kanagawa/config --style ~/.config/waybar/kanagawa/style.css
exec = [ "$(pgrep swaybg)" ] && pkill swaybg; swaybg -i $(find $HOME/Pictures/Wallpapers/Kanagawa/. -type f | shuf -n1)
exec = [ "$(pgrep swaybg)" ] && pkill gammastep; gammastep -P -O 3600 &

exec = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'
exec = gsettings set org.gnome.desktop.interface gtk-theme 'kanagawa'
exec = gsettings set org.gnome.desktop.interface icon-theme 'Papirus'

# vim:ft=bash
